[package]
name = "glutin_examples"
version = "0.1.2"
authors = ["The glutin contributors", "Hal Gentz <zegentzy@protonmail.com>"]
description = "Examples for glutin"
repository = "https://github.com/rust-windowing/glutin"
license = "Apache-2.0"
readme = "../README.md"
build = "build.rs"
edition = "2018"
publish = false

[dependencies]
glutin = { path = "../glutin" }
takeable-option = "0.4"
image = "0.21"
glium = "0.30.1"
glium-glyph = { git = "https://github.com/ngynkvn/glium-glyph" }
nalgebra-glm = "0.14.0"

[build-dependencies]
gl_generator = "0.14"
